// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9cbJYUy-DODGBngSOsysqyZsvTAxL22I',
    appId: '1:905947356572:web:00ad3cecc8636a021dbc59',
    messagingSenderId: '905947356572',
    projectId: 'traductionapprentissagelangues',
    authDomain: 'traductionapprentissagelangues.firebaseapp.com',
    storageBucket: 'traductionapprentissagelangues.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_izkYtlzc6TzkQOb8g9RP3lqbq_BGCEI',
    appId: '1:905947356572:android:3f7ffdc07096b9fd1dbc59',
    messagingSenderId: '905947356572',
    projectId: 'traductionapprentissagelangues',
    storageBucket: 'traductionapprentissagelangues.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZbaU_jEqzn3FuxqU1VWzJuKD04uOzKE',
    appId: '1:905947356572:ios:cd194dc28747c83e1dbc59',
    messagingSenderId: '905947356572',
    projectId: 'traductionapprentissagelangues',
    storageBucket: 'traductionapprentissagelangues.appspot.com',
    iosBundleId: 'com.example.traductionAprentissageLangues',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHZbaU_jEqzn3FuxqU1VWzJuKD04uOzKE',
    appId: '1:905947356572:ios:d7ae3e2c8633f4501dbc59',
    messagingSenderId: '905947356572',
    projectId: 'traductionapprentissagelangues',
    storageBucket: 'traductionapprentissagelangues.appspot.com',
    iosBundleId: 'com.example.traductionAprentissageLangues.RunnerTests',
  );
}
